# Generated by Django 2.1.7 on 2019-03-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='img',
            field=models.URLField(max_length=400),
        ),
    ]
