# Generated by Django 2.1.7 on 2019-03-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS', '0002_auto_20190322_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='img',
            field=models.CharField(max_length=400),
        ),
    ]
