# Generated by Django 2.1.7 on 2019-03-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RSS', '0003_auto_20190322_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='pubDate',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
