# Generated by Django 2.1.7 on 2019-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSfeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('creator', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=300)),
                ('pubDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('img', models.URLField(blank=True)),
            ],
        ),
    ]
